config/routes.rb
Rails.application.routes.draw do
  resources :hubs
  # root 'welcome#index'
  resources :hubs do
    put 'hubs/:id' => 'hubs#update'
    match '/scrape', to: 'hubs#scrape', via: :post, on: :collection
  end

  root to: 'hubs#index'

  get '*path', to: 'pages#index', via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hub.rb
class Hub < ApplicationRecord
end

app/models/hubs_spider.rb
class HubsSpider < Kimurai::Base
  @name = 'hubs_spider'
  @engine = :mechanize

  def self.process(url)
    @start_urls = [url]
    self.crawl!
  end

  def parse(response, url:, data: {})
    item = {}
    item[:active] = response.xpath("//div[@class='proxy']").count
    item[:hub_number] = url.match(/selenium-hub(\d+)/)[1]
    hub = Hub.where(hub_number: item[:hub_number]).first_or_create
    hub.update!(active: item[:active], url: url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper Webpacker::Helper
end

app/controllers/hubs_controller.rb
class HubsController < ApplicationController
  before_action :set_hub, only: [:show, :edit, :update, :destroy]

  # GET /hubs
  # GET /hubs.json
  def index
    @hubs = Hub.all

    respond_to do |format|
      format.html
      format.json { render json: @hubs }
    end
  end

  def scrape
    urls.each do |url|
      response = HubsSpider.process(url)
      if response[:status] == :completed && response[:error].nil?
        flash.now[:notice] = "Successfully scraped url"
      else
        flash.now[:alert] = response[:error]
      end
    rescue StandardError => e
      flash.now[:alert] = "Error: #{e}"
    end
  end

  # GET /hubs/1
  # GET /hubs/1.json
  def show
  end

  # GET /hubs/new
  def new
    @hub = Hub.new
  end

  # GET /hubs/1/edit
  def edit
  end

  # POST /hubs
  # POST /hubs.json
  def create
    @hub = Hub.new(hub_params)

    respond_to do |format|
      if @hub.save
        format.html { redirect_to @hub, notice: 'Hub was successfully created.' }
        format.json { render :show, status: :created, location: @hub }
      else
        format.html { render :new }
        format.json { render json: @hub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hubs/1
  # PATCH/PUT /hubs/1.json
  def update
    respond_to do |format|
      if @hub.update(hub_params)
        format.html { redirect_to @hub, notice: 'Hub was successfully updated.' }
        format.json { render :show, status: :ok, location: @hub }
      else
        format.html { render :edit }
        format.json { render json: @hub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hubs/1
  # DELETE /hubs/1.json
  def destroy
    @hub.destroy
    respond_to do |format|
      format.html { redirect_to hubs_url, notice: 'Hub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hub
      @hub = Hub.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hub_params
      params.require(:hub).permit(:active, :inactive)
    end

    def urls
      [
        'http://selenium-hub-easyjet-scrape1.aero.otbeach.com:4444/grid/console',
        'http://selenium-hub-testing1.aero.otbeach.com:4444/grid/console',
        'http://selenium-hub-email1.aero.otbeach.com:4444/grid/console',
        'http://selenium-hub-booking1.aero.otbeach.com:4444/grid/console',
        'http://selenium-hub-jet2-scrape1.aero.otbeach.com:4444/grid/console',
        'http://selenium-hub-deal-pricing1.aero.otbeach.com:4444/grid/console',
        'http://selenium-hub-scheduling1.aero.otbeach.com:4444/grid/console'
      ]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hubs_helper.rb
module HubsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hubs/_form.html.erb
<%= form_with(model: hub, local: true) do |form| %>
  <% if hub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hub.errors.count, "error") %> prohibited this hub from being saved:</h2>

      <ul>
        <% hub.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :active %>
    <%= form.number_field :active %>
  </div>

  <div class="field">
    <%= form.label :inactive %>
    <%= form.number_field :inactive %>
  </div>

  <div class="field">
    <%= form.label :hub_number %>
    <%= form.number_field :hub_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hubs/edit.html.erb
<h1>Editing Hub</h1>

<%= render 'form', hub: @hub %>

<%= link_to 'Show', @hub %> |
<%= link_to 'Back', hubs_path %>

app/views/hubs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid centered">
  <%# <h1>Selenium Hubs with their Active nodes</h1> %>

  <body>
    <%= react_component('Tables', hubs: @hubs) %>
    <br>

    <%= link_to 'New Hub', new_hub_path %>

    <div id="root"></div>

  <body>
</div>

app/views/hubs/new.html.erb
<h1>New Hub</h1>

<%= render 'form', hub: @hub %>

<%= link_to 'Back', hubs_path %>

app/views/hubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Active:</strong>
  <%= @hub.active %>
</p>

<p>
  <strong>Inactive:</strong>
  <%= @hub.inactive %>
</p>

<p>
  <strong>Hub number:</strong>
  <%= @hub.hub_number %>
</p>

<%= link_to 'Edit', edit_hub_path(@hub) %> |
<%= link_to 'Back', hubs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewReactApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    
  </head>

  <body>
    <nav class="navbar navbar-inverse head-color">
      <img class="logo-area" href="/" src="/logo.png"></img>
      <form class="form-inline">
        <%# <a class="btn btn-outline-primary" href="/login" role="button"> %>
        <%# Login %>
        <%# </a> %>
        <div style="padding-left: 10px;">
          <%= link_to 'Check Active Nodes', scrape_hubs_path, method: :post, class: 'btn btn-outline-success scrape-btn' %>
        </div>
      </form>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h2>WELCOME</h2>

<%= javascript_pack_tag 'hello_react' %>